src/Entity/Item.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Item
 *
 * @ORM\Table(name="item")
 * @ORM\Entity
 */
class Item
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Destination", inversedBy="items")
     * @ORM\JoinColumn(nullable=true)
     */
    private $destination;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Fabricant", inversedBy="items")
     */
    private $fabricant;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $reference_fabricant;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    private $designation;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Illustration", mappedBy="item")
     */
    private $illustrations;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", mappedBy="items")
     */
    private $users;

    public function __construct()
    {
        $this->illustrations = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getDestination(): ?Destination
    {
        return $this->destination;
    }

    public function setDestination(?Destination $destination): self
    {
        $this->destination = $destination;

        return $this;
    }

    public function getFabricant(): ?Fabricant
    {
        return $this->fabricant;
    }

    public function setFabricant(?Fabricant $fabricant): self
    {
        $this->fabricant = $fabricant;

        return $this;
    }

    public function getReferenceFabricant(): ?string
    {
        return $this->reference_fabricant;
    }

    public function setReferenceFabricant(?string $reference_fabricant): self
    {
        $this->reference_fabricant = $reference_fabricant;
        return $this;
    }

	public function __toString() {
        return "Item ".$this->id." (".$this->destination." - ".$this->designation.")";
    }

    public function getDesignation(): ?string
    {
        return $this->designation;
    }

    public function setDesignation(?string $designation): self
    {
        $this->designation = $designation;
        return $this;
    }

    /**
     * @return Collection|Illustration[]
     */
    public function getIllustrations(): Collection
    {
        return $this->illustrations;
    }
	
	public function getMainIllustration(): ?Illustration
    {
        foreach ($this->illustrations as $illu)
		{
			if ($illu->getIsMain())
				return $illu ;
		}
		return null ;
    }

    public function addIllustration(Illustration $illustration): self
    {
        if (!$this->illustrations->contains($illustration)) {
            $this->illustrations[] = $illustration;
            $illustration->setItem($this);
        }

        return $this;
    }

    public function removeIllustration(Illustration $illustration): self
    {
        if ($this->illustrations->contains($illustration)) {
            $this->illustrations->removeElement($illustration);
            // set the owning side to null (unless already changed)
            if ($illustration->getItem() === $this) {
                $illustration->setItem(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addItem($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            $user->removeItem($this);
        }

        return $this;
    }


}

src/Form/ItemType.php
<?php

namespace App\Form;

use App\Entity\Item;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ItemType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('reference_fabricant')
            ->add('destination')
            ->add('fabricant')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Item::class,
        ]);
    }
}

src/Controller/ItemController.php
<?php

namespace App\Controller;

use App\Entity\Item;
use App\Entity\Destination;
use App\Form\ItemType;
use App\Controller\DestinationController;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Psr\Log\LoggerInterface;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Logger\ConsoleLogger;

/**
 * @Route("/item")
 */
class ItemController extends AbstractController
{
	
    /**
     * @Route("/", name="item_index", methods={"GET"})
     */
    public function index(): Response
    {
        $items = $this->getDoctrine()
            ->getRepository(Item::class)
            ->findAll();

        return $this->render('item/index.html.twig', [
            'items' => $items,
        ]);
    }

    /**
     * @Route("/new", name="item_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $item = new Item();
        $form = $this->createForm(ItemType::class, $item);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($item);
            $entityManager->flush();

            return $this->redirectToRoute('item_index');
        }

        return $this->render('item/new.html.twig', [
            'item' => $item,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="item_show", methods={"GET"})
     */
    public function show(Item $item): Response
    {
		$gotitem = false ;
		try {
			$user = $this->getUser();
			
			if ($item->getUsers()->contains($this->getUser()))
				$gotitem = true ;
			
		}
		catch (Exception $e) {
			$user = null ;
		}

        $arbo = $item->getDestination()->getArbo() ;
		
		return $this->render('item/show.html.twig', [
            'item' => $item,
			'arbo' => $arbo,
			'user' => $user,
			'gotitem' => $gotitem
        ]);
    }
	

    /**
     * @Route("/{id}/edit", name="item_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Item $item): Response
    {
        $form = $this->createForm(ItemType::class, $item);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('item_index', [
                'id' => $item->getId(),
            ]);
        }

        return $this->render('item/edit.html.twig', [
            'item' => $item,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="item_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Item $item): Response
    {
        if ($this->isCsrfTokenValid('delete'.$item->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($item);
            $entityManager->flush();
        }

        return $this->redirectToRoute('item_index');
    }
}

templates/item/_delete_form.html.twig
<form method="post" action="{{ path('item_delete', {'id': item.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ item.id) }}">
    <button class="btn">Delete</button>
</form>

templates/item/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/item/destination.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste{% endblock %}

{% block hero %}

	<section class="hero is-primary">
	  <div class="hero-body">
		<div class="container">
		  <h1 class="title">
			{{ destination.name }}
		  </h1>
		</div>
	  </div>
	  <div class="hero-foot">
		<nav class="tabs is-boxed">
		  <div class="container">
			<ul>
				<li class="is-active"><a>Résumé</a></li>
			  	<li><a>Ecussons {{ destination.name }} ({{ destination.items.count }})</a></li>
			  	<li><a>Destinations {{ destination.name }}</a></li>
				<li><a>Ecussons dans {{ destination.name }} </a></li>
			</ul>
		  </div>
		</nav>
		</div>
	</section>
{% endblock %}   
{% block body %}

	{% if page == "resume" %}
		<div class="columns">
			<div class="column has-background-primary has-text-white">
				<span class="is-pulled-right">{{ destination.items.count }} écussons</span>
				<h1>Ecussons {{ destination.name }}</h1>
			</div>
		</div>

		<div class="columns is-multiline is-mobile">

			{% for item_under in destination.items %}

				<div class="column is-half-mobile is-half-tablet is-one-quarter-desktop is-one-quarter-widescreen is-one-quarter-fullhd">
					<a href="{{ path('item_show', {'id': item_under.id}) }}">
						<div style="background-color:white;height:100%;box-shadow: 0px 0px 5px 2px rgba(0, 0, 0, .1);">
							<div style="height:70px; padding:10px;overflow:hidden;line-height:20px;background-color:moccasin;text-align:center;display:flex;align-items:center;justify-content:center">
								<p>
									<span><b>{{ item_under.destination.name }}</b></span><br />
									<span style="font-size:0.7em">{{ item_under.destination.parent.name }}</span>
								</p>
							</div>

							{% include 'site/includes/illustration.html.twig' with {'item_under': item_under} %}

							<div style="height:70px; padding:10px;overflow:hidden;line-height:20px;background-color:#eeeeee;text-align:center;display:flex;align-items:center;justify-content:center">
								<span>{{ item_under.designation }}</span>
							</div>
						</div>
					</a>
				</div>

			{% endfor %}

		</div>

	{% endif %}

	<h1>Ecussons {{ destination.name }}</h1>


	<div class="navigation">
        {{ knp_pagination_render(pagination) }}
    </div>
	
{% endblock %}

templates/item/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Item{% endblock %}

{% block body %}
    <h1>Edit Item</h1>

    {{ include('item/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('item_index') }}">back to list</a>

    {{ include('item/_delete_form.html.twig') }}
{% endblock %}

templates/item/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Item index{% endblock %}

{% block body %}
    <h1>Item index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Reference_fabricant</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for item in items %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.referenceFabricant }}</td>
                <td>
                    <a href="{{ path('item_show', {'id': item.id}) }}">show</a>
                    <a href="{{ path('item_edit', {'id': item.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('item_new') }}">Create new</a>
{% endblock %}

templates/item/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Item{% endblock %}

{% block body %}
    <h1>Create new Item</h1>

    {{ include('item/_form.html.twig') }}

    <a href="{{ path('item_index') }}">back to list</a>
{% endblock %}

templates/item/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ecusson - {{ item.designation }}{% endblock %}

{% block hero %}
	<section class="hero is-primary">
	  <div class="hero-body">
		<div class="container">
            <h1 class="title">
                {{ item.designation }}
            </h1>
            <h2 class="subtitle">
                Ecusson
            </h2>
		</div>
	  </div>
	</section>
{% endblock %}
{% block body %}


<div class="columns">
    <div class="column">

        <div class="box">
            {% for dest in arbo %}
                {% if not loop.first %} > {% endif %}
                <a href="{{ path('destination_list', {'slug': dest.slug}) }}">{{ dest }}</a>
            {% endfor %}
        </div>
        <div class="box">
            <article class="media">
                <div class="media-content">
                    <div class="content">
                        <p>
                            <strong>Références fabricant</strong>
                            <br />
                            <b>Fabricant :</b> {% if item.fabricant is not none %}{{ item.fabricant.nom }}{% else %}Inconnu{% endif %}
                            <br />
                            <b>Réference fabricant :</b> {{ item.referenceFabricant }}
                            <br>
                            <b>Désignation :</b> {{ item.designation }}
                        </p>
                    </div>
                </div>
            </article>
        </div>
        <div class="box">
            <article class="media">
                <div class="media-content">
                    <div class="content">
                        <p>
                            <strong>Références site</strong>
                            <br>
                            <b>Identifiant :</b> {{ item.id }}
                        </p>
                    </div>
                </div>
            </article>
        </div>
        <div class="box">
            <article class="media">
                <div class="media-content">
                    <div class="content">
                        <p>
                            {% if user %}
                                <button onclick="gotitem()" class="button is-primary is-pulled-right">Modifier</button>
                            {% endif %}
                            <strong>Votre collection</strong>
                            <br>
                            {% if user %}
                                <span id="gotit">
                                    <span id="gotit_yes"{% if not gotitem %} class="is-hidden"{% endif %}>Vous avez cet écusson.</span>
                                    <span id="gotit_no"{% if gotitem %} class="is-hidden"{% endif %}>Vous n'avez pas cet écusson.</span>
                                </span>
                            {% else %}
                                Vous n'êtes pas connecté.
                            {% endif %}
                        </p>
                    </div>
                </div>
            </article>
        </div>


    </div>
    <div class="column">
        <div class="box">
            {% if item.illustrations is empty %}
                Pas d'illustration.
            {% else %}
                {% for illustration in item.illustrations %}
                    {% include 'site/includes/illustration.html.twig' with {'illustration': illustration} %}
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}
<script type="text/javascript" language="javascript">

    function gotitem() {

        var httpRequest = false;

        httpRequest = new XMLHttpRequest();

        if (!httpRequest) {
            alert('Abandon :( Impossible de créer une instance XMLHTTP');
            return false;
        }
        httpRequest.onreadystatechange = function() {

            if (httpRequest.readyState == XMLHttpRequest.DONE) {
                if (httpRequest.status == 200) {
                    var data = JSON.parse(httpRequest.responseText);
                    if (data.data) {
                        document.getElementById('gotit_yes').classList.remove("is-hidden");
                        document.getElementById('gotit_no').classList.add("is-hidden");
                    }
                    else {
                        document.getElementById('gotit_no').classList.remove("is-hidden");
                        document.getElementById('gotit_yes').classList.add("is-hidden");
                    }

                } else {
                    alert('Un problème est survenu avec la requête.');
                }
            }

        };
        httpRequest.open('GET', '{{ path('user_gotitem', {'id': item.id}) }}', true);
        httpRequest.send();

    }

</script>
{% endblock %}